### ISSUE TITLE
Crash: 5950912157221228609

### ISSUE THREAD

**Issue by tigerbeetle-vopr** [tigerbeetle/tigerbeetle#743] opened 2023-05-01 12:12 UTC
<strong>Commit:</strong> ```4a976a08b76de6f13bcda4f74a3432938897ed56``` <br><br><strong>Branches:</strong> main<br><br><strong>Duration to run seed in ReleaseSafe mode:</strong> 3s<br><br><strong>Stack Trace:</strong><br>
```
thread panic: reached unreachable code
src/vsr/journal.zig:0:0: in vsr.journal.JournalType(vsr.replica.ReplicaType(state_machine.StateMachineType(testing.storage.Storage,(struct constants.StateMachineConfig constant)),testing.cluster.message_bus.MessageBus,testing.storage.Storage,testing.time.Time,testing.aof.AOF),testing.storage.Storage).read_prepare_with_op_and_checksum (simulator)
src/testing/storage.zig:274:31: in testing.storage.Storage.tick (simulator)
next_tick.callback(next_tick);

src/testing/cluster.zig:312:59: in testing.cluster.ClusterType(state_machine.StateMachineType).tick (simulator)
for (cluster.storages) |*storage| storage.tick();

src/simulator.zig:352:31: in main (simulator)
simulator.cluster.tick();

zig/lib/std/start.zig:561:37: in std.start.posixCallMainAndExit (simulator)
const result = root.main() catch |err| {

zig/lib/std/start.zig:322:5: in std.start._start (simulator)
@call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});

debug: exit with signal: 6. Indicates a crash bug.


```
<br><strong>Debug Logs:</strong><br><details><summary>Tail</summary><br>
```debug: Replaying seed 5950912157221228609 in Debug mode with full debug logging enabled...


SEED=5950912157221228609

replicas=3
standbys=1
clients=6
request_probability=3%
idle_on_probability=19%
idle_off_probability=14%
one_way_delay_mean=9 ticks
one_way_delay_min=2 ticks
packet_loss_probability=20%
path_maximum_capacity=3 messages
path_clog_duration_mean=318 ticks
path_clog_probability=1%
packet_replay_probability=5%
partition_mode=PartitionMode.isolate_single
partition_symmetry=PartitionSymmetry.asymmetric
partition_probability=1%
unpartition_probability=3%
partition_stability=185 ticks
unpartition_stability=4 ticks
read_latency_min=0
read_latency_mean=10
write_latency_min=1
write_latency_mean=6
read_fault_probability=8%
write_fault_probability=5%
crash_probability=0.00002%
crash_stability=192 ticks
restart_probability=0.0002%
restart_stability=533 ticks
 2/.2V1/__1C0:__2Jo0/_0J!0:4Wo45056Gf2/4Pp0/3Pq
 0\ .2V1/__1C0:__3Jo0/_2J!0:1Wo45056Gf
 1/v4V1/__1C0:__3Jo0/_1J!0:4Wo45056Gf
 3|.5V1/__1C0:__5Jo0/_3J!0:4Wo45056Gf
 2/.5V2/__2C0:__5Jo0/_0J!0:5Wo45056Gf4/4Pp1/3Pq
 3|.5V2/__2C0:__5Jo0/_1J!0:4Wo45056Gf
 0\ .5V2/__2C0:__6Jo0/_2J!0:6Wo45056Gf
 1\.5V2/__2C0:__6Jo0/_1J!0:6Wo45056Gf
 0/ .6V3/__3C0:__6Jo0/_0J!0:6Wo45056Gf4/4Pp1/3Pq
 0/ .6V4/__4C0:__7Jo0/_1J!0:6Wo45056Gf4/4Pp0/3Pq
 1\.6V3/__3C0:__7Jo0/_1J!0:7Wo45056Gf
 1\.6V4/__4C0:__7Jo0/_0J!0:7Wo45056Gf
 3|.6V3/__4C0:__6Jo0/_0J!0:6Wo45056Gf
 3|.6V4/__4C0:__6Jo0/_0J!0:6Wo45056Gf
 0/ .6V5/__5C0:__8Jo0/_0J!0:8Wo45056Gf4/4Pp0/3Pq
 0/ .6V6/__6C0:__8Jo0/_0J!0:8Wo45056Gf3/4Pp0/3Pq
 1\.6V5/__6C0:__9Jo0/_1J!0:8Wo45056Gf
 1\.6V6/__6C0:__9Jo0/_1J!0:8Wo45056Gf
 3|.6V5/__6C0:__6Jo0/_0J!0:6Wo45056Gf
 3|.6V6/__6C0:__6Jo0/_0J!0:6Wo45056Gf
 2\.6V3/__6C0:__9Jo0/_3J!0:6Wo45056Gf
 2\.6V4/__6C0:__9Jo0/_3J!0:6Wo45056Gf
 2\.6V5/__6C0:__9Jo0/_3J!0:6Wo45056Gf
 2\.6V6/__6C0:__9Jo0/_3J!0:6Wo45056Gf
 0/ .6V7/__7C0:_10Jo0/_0J!0: 10Wo45056Gf4/4Pp0/3Pq
 2\.6V7/__7C0:__9Jo0/_0J!0:9Wo45056Gf
 1\.6V7/__7C0:_10Jo0/_0J!0: 10Wo45056Gf
 3|.6V7/__7C0:_11Jo0/_4J!0: 10Wo45056Gf
 0/ .6V8/__8C0:_11Jo0/_0J!0: 11Wo45056Gf4/4Pp2/3Pq
 0/ .6V9/__9C0:_12Jo0/_1J!0: 11Wo45056Gf4/4Pp1/3Pq
 0/ .6V10/_10C0:_13Jo0/_2J!0: 11Wo45056Gf4/4Pp0/3Pq
 3|.6V8/_10C0:_11Jo0/_0J!0: 11Wo45056Gf
 3|.6V9/_10C0:_11Jo0/_0J!0: 11Wo45056Gf
 3|.6V10/_10C0:_11Jo0/_0J!0: 11Wo45056Gf
 0/ .6V11/_11C0:_14Jo0/_0J!0: 14Wo45056Gf4/4Pp0/3Pq
 1\.6V8/_10C0:_14Jo0/_1J!0: 14Wo45056Gf
 1\.6V9/_10C0:_14Jo0/_1J!0: 14Wo45056Gf
 1\.6V10/_10C0:_14Jo0/_1J!0: 14Wo45056Gf
 1\.6V11/_11C0:_14Jo0/_1J!0: 14Wo45056Gf
 0/ .6V12/_12C0:_15Jo0/_0J!0: 15Wo45056Gf4/4Pp0/3Pq
 1\.6V12/_12C0:_15Jo0/_0J!0: 15Wo45056Gf
 0/ .6V13/_13C0:_16Jo0/_0J!0: 16Wo45056Gf4/4Pp0/3Pq
 0/ .6V14/_14C0:_16Jo0/_0J!0: 16Wo45056Gf3/4Pp0/3Pq
 1\.6V13/_14C0:_17Jo0/_1J!0: 16Wo45056Gf
 1\.6V14/_14C0:_17Jo0/_1J!0: 16Wo45056Gf
 3|.6V11/_14C0:_15Jo0/_3J!0: 15Wo45056Gf
 2\.6V8/_14C0:_17Jo0/_4J!0: 17Wo45056Gf
 2\.6V9/_14C0:_17Jo0/_4J!0: 17Wo45056Gf
 2\.6V10/_14C0:_17Jo0/_2J!0: 17Wo45056Gf
 2\.6V11/_14C0:_17Jo0/_2J!0: 17Wo45056Gf
 2\.6V12/_14C0:_17Jo0/_2J!0: 17Wo45056Gf
 3|.6V12/_14C0:_15Jo0/_0J!0: 15Wo45056Gf
 3|.6V13/_14C0:_15Jo0/_0J!0: 15Wo45056Gf
 3|.6V14/_14C0:_15Jo0/_0J!0: 15Wo45056Gf
 2\.6V13/_14C0:_17Jo0/_0J!0: 17Wo45056Gf
 2\.6V14/_14C0:_17Jo0/_0J!0: 17Wo45056Gf
 0/ .9V15/_15C0:_18Jo0/_0J!0: 18Wo45056Gf4/4Pp1/3Pq
 1\.9V15/_15C0:_19Jo0/_2J!0: 17Wo45056Gf
 3|.9V15/_15C0:_19Jo0/_4J!0: 15Wo45056Gf
 0/ .9V16/_16C0:_19Jo0/_0J!0: 19Wo45056Gf4/4Pp1/3Pq
 0/ .9V17/_17C0:_20Jo0/_1J!0: 19Wo45056Gf4/4Pp0/3Pq
 1\.9V16/_16C0:_20Jo0/_1J!0: 19Wo45056Gf
 1\.9V17/_17C0:_20Jo0/_1J!0: 19Wo45056Gf
 2\.9V15/_17C0:_20Jo0/_2J!0: 18Wo45056Gf
 2\.9V16/_17C0:_20Jo0/_2J!0: 18Wo45056Gf
```
</details>

**Comment by matklad** [comment] 2023-05-02 14:00
dupe of #749

**Closed as completed by matklad** 2023-05-02 14:00 UTC
