### ISSUE TITLE
Crash: 7064100283233245564

### ISSUE THREAD

**Issue by tigerbeetle-vopr** [tigerbeetle/tigerbeetle#1590] opened 2024-02-24 17:37 UTC
<strong>Commit:</strong> ```fcc1323e6b700f8212eed1da9aa202b1d902556e``` <br><br><strong>Branches:</strong> main<br><br><strong>Duration to run seed in ReleaseSafe mode:</strong> 6s<br><br><strong>Stack Trace:</strong><br>
```
thread panic: reached unreachable code
src/vsr/replica.zig:0:76: in valid_hash_chain_between (simulator)
src/vsr/replica.zig:5395:49: in repair (simulator)
assert(self.valid_hash_chain_between(self.op_repair_min(), self.op));

src/vsr/replica.zig:2781:24: in tick (simulator)
self.repair();

src/testing/cluster.zig:356:37: in tick (simulator)
replica.tick();

src/simulator.zig:253:23: in main (simulator)
simulator.tick();

zig/lib/std/start.zig:574:37: in posixCallMainAndExit (simulator)
const result = root.main() catch |err| {

zig/lib/std/start.zig:243:5: in _start (simulator)
asm volatile (switch (native_arch) {

???:?:?: in ??? (???)
Unwind information for `???:0x1` was not available, trace may be incomplete

debug: exit with signal: 6. Indicates a crash bug.


```
<br><strong>Debug Logs:</strong><br><details><summary>Tail</summary><br>
```debug: Replaying seed 7064100283233245564 in Debug mode with full debug logging enabled...


SEED=7064100283233245564

replicas=3
standbys=6
clients=7
request_probability=9%
idle_on_probability=6%
idle_off_probability=15%
one_way_delay_mean=11 ticks
one_way_delay_min=2 ticks
packet_loss_probability=21%
path_maximum_capacity=17 messages
path_clog_duration_mean=406 ticks
path_clog_probability=1%
packet_replay_probability=39%
partition_mode=testing.packet_simulator.PartitionMode.uniform_size
partition_symmetry=testing.packet_simulator.PartitionSymmetry.asymmetric
partition_probability=1%
unpartition_probability=7%
partition_stability=108 ticks
unpartition_stability=16 ticks
read_latency_min=0
read_latency_mean=8
write_latency_min=0
write_latency_mean=25
read_fault_probability=4%
write_fault_probability=4%
crash_probability=0.00002%
crash_stability=953 ticks
restart_probability=0.0002%
restart_stability=427 ticks
 1/.1V0/__1/__1C0:__4Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?3/4Pp1/3Rq
 1/.1V0/__2/__2C0:__5Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?3/4Pp0/3Rq
 2\.1V0/__1/__1C0:__5Jo0/_4J!0:_31Wo <__0:__0>0Ga0G!0G?
 0\ .1V0/__1/__1C0:__5Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.1V0/__1/__2C0:__5Jo0/_5J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.1V0/__2/__2C0:__5Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 0\ .1V0/__2/__2C0:__5Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 7|.1V0/__1/__2C0:__4Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 7|.1V0/__2/__2C0:__4Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 5|.1V0/__1/__2C0:__4Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 6|.1V0/__1/__2C0:__5Jo0/_5J!0:_31Wo <__0:__0>0Ga0G!0G?
 5|.1V0/__2/__2C0:__4Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 8|.1V0/__1/__2C0:__5Jo0/_5J!0:_31Wo <__0:__0>0Ga0G!0G?
 8|.1V0/__2/__2C0:__5Jo0/_5J!0:_31Wo <__0:__0>0Ga0G!0G?
 1/.1V0/__3/__3C0:__6Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?3/4Pp0/3Rq
 1/.1V0/__4/__4C0:__6Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?2/4Pp0/3Rq
 1/.1V0/__5/__5C0:__6Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?1/4Pp0/3Rq
 0\ .1V0/__3/__5C0:__5Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 0\ .1V0/__4/__5C0:__5Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 0\ .1V0/__5/__5C0:__5Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.1V0/__3/__5C0:__5Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.1V0/__4/__5C0:__5Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.1V0/__5/__5C0:__5Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 8|.1V0/__3/__5C0:__5Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 8|.1V0/__4/__5C0:__5Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 8|.1V0/__5/__5C0:__5Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 5|.1V0/__3/__5C0:__9Jo0/_5J!0:_31Wo <__0:__0>0Ga0G!0G?
 5|.1V0/__4/__5C0:__9Jo0/_5J!0:_31Wo <__0:__0>0Ga0G!0G?
 7|.1V0/__3/__5C0:__9Jo0/_5J!0:_31Wo <__0:__0>0Ga0G!0G?
 7|.1V0/__4/__5C0:__9Jo0/_5J!0:_31Wo <__0:__0>0Ga0G!0G?
 7|.1V0/__5/__5C0:__9Jo0/_5J!0:_31Wo <__0:__0>0Ga0G!0G?
 5|.1V0/__5/__5C0:__9Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?
 2\.1V0/__2/__5C0:__9Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 2\.1V0/__3/__5C0:__9Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 2\.1V0/__4/__5C0:__9Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 2\.1V0/__5/__5C0:__9Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 1/.1V0/__6/__6C0:__9Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?3/4Pp2/3Rq
 2\.1V0/__6/__6C0:_10Jo0/_4J!0:_31Wo <__0:__0>0Ga0G!0G?
 5|.1V0/__6/__6C0:__9Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 0\ .1V0/__6/__6C0:__9Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 1/.1V0/__7/__7C0:_10Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?3/4Pp3/3Rq
 0\ .1V0/__7/__7C0:__9Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 8|.1V0/__6/__7C0:_11Jo0/_6J!0:_31Wo <__0:__0>0Ga0G!0G?
 8|.1V0/__7/__7C0:_11Jo0/_6J!0:_31Wo <__0:__0>0Ga0G!0G?
 5|.1V0/__7/__7C0:__9Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 4|.1V0/__1/__6C0:_10Jo0/10J!0:_31Wo <__0:__0>0Ga0G!0G?
 4|.1V0/__2/__6C0:_10Jo0/10J!0:_31Wo <__0:__0>0Ga0G!0G?
 4|.1V0/__3/__6C0:_10Jo0/10J!0:_31Wo <__0:__0>0Ga0G!0G?
 4|.1V0/__4/__6C0:_10Jo0/10J!0:_31Wo <__0:__0>0Ga0G!0G?
 4|.1V0/__5/__6C0:_10Jo0/_8J!0:_31Wo <__0:__0>0Ga0G!0G?
 4|.1V0/__6/__6C0:_10Jo0/_8J!0:_31Wo <__0:__0>0Ga0G!0G?
 4|.1V0/__7/__7C0:_10Jo0/_4J!0:_31Wo <__0:__0>0Ga0G!0G?
 1/.1V0/__8/__8C0:_11Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?3/4Pp3/3Rq
 1/.1V0/__9/__9C0:_12Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?3/4Pp2/3Rq
 5|.1V0/__8/__9C0:__9Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 5|.1V0/__9/__9C0:__9Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 8|.1V0/__8/__9C0:_11Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 8|.1V0/__9/__9C0:_11Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 4|.1V0/__8/__9C0:_10Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 4|.1V0/__9/__9C0:_10Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 0\ .1V0/__8/__9C0:__9Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 0\ .1V0/__9/__9C0:_10Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 1/.1V0/_10/_10C0:_13Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?3/4Pp1/3Rq
 6|.1V0/__2/__9C0:_13Jo0/_8J!0:_31Wo <__0:__0>0Ga0G!0G?
 6|.1V0/__3/__9C0:_13Jo0/_8J!0:_31Wo <__0:__0>0Ga0G!0G?
 6|.1V0/__4/__9C0:_13Jo0/_8J!0:_31Wo <__0:__0>0Ga0G!0G?
 6|.1V0/__5/__9C0:_13Jo0/_8J!0:_31Wo <__0:__0>0Ga0G!0G?
 4|.1V0/_10/_10C0:_10Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 8|.1V0/_10/_10C0:_11Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 6|.1V0/__6/_10C0:_13Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?
 6|.1V0/__7/_10C0:_13Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?
 6|.1V0/__8/_10C0:_13Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?
 6|.1V0/__9/_10C0:_13Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?
 6|.1V0/_10/_10C0:_13Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?
 2\.1V0/__7/_10C0:_11Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 2\.1V0/__8/_10C0:_11Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 2\.1V0/__9/_10C0:_11Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 2\.1V0/_10/_10C0:_11Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 0\ .1V0/_10/_10C0:_11Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.1V0/__6/_10C0:_14Jo0/_9J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.1V0/__7/_10C0:_14Jo0/_9J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.1V0/__8/_10C0:_14Jo0/_9J!0:_31Wo <__0:__0>0Ga0G!0G?
 5|.1V0/_10/_10C0:_14Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.1V0/__9/_10C0:_14Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.1V0/_10/_10C0:_14Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 1/.1V0/_11/_11C0:_14Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?3/4Pp2/3Rq
 4|.1V0/_11/_11C0:_11Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 8|.1V0/_11/_11C0:_11Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 5|.1V0/_11/_11C0:_14Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 0\ .1V0/_11/_11C0:_11Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.1V0/_11/_11C0:_14Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 6|.1V0/_11/_11C0:_13Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 2\.1V0/_11/_11C0:_15Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 7|.1V0/__6/_11C0:_15Jo0/_6J!0:_31Wo <__0:__0>0Ga0G!0G?
 7|.1V0/__7/_11C0:_15Jo0/_6J!0:_31Wo <__0:__0>0Ga0G!0G?
 7|.1V0/__8/_11C0:_15Jo0/_6J!0:_31Wo <__0:__0>0Ga0G!0G?
 7|.1V0/__9/_11C0:_15Jo0/_6J!0:_31Wo <__0:__0>0Ga0G!0G?
 7|.2V0/_10/_11C0:_15Jo0/_6J!0:_31Wo <__0:__0>0Ga0G!0G?
 7|.2V0/_11/_11C0:_15Jo0/_6J!0:_31Wo <__0:__0>0Ga0G!0G?
 2/.2V0/_12/_12C0:_15Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?3/4Pp2/3Rq
 4|.2V0/_12/_12C0:_16Jo0/_5J!0:_31Wo <__0:__0>0Ga0G!0G?
 0\ .2V0/_12/_12C0:_16Jo0/_4J!0:_31Wo <__0:__0>0Ga0G!0G?
 6|.2V0/_12/_12C0:_15Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 1\.2V0/_12/_12C0:_16Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 8|.2V0/_12/_12C0:_15Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 2/.2V0/_13/_13C0:_16Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?3/4Pp2/3Rq
 0\ .2V0/_13/_13C0:_17Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?
 7|.2V0/_12/_12C0:_15Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 7|.2V0/_13/_13C0:_15Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 2/.2V0/_14/_14C0:_17Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?3/4Pp1/3Rq
 2/.2V0/_15/_15C0:_18Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?3/4Pp0/3Rq
 0\ .2V0/_14/_14C0:_18Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?
 8|.2V0/_13/_15C0:_15Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 8|.2V0/_14/_15C0:_15Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 8|.2V0/_15/_15C0:_15Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 5|.2V0/_12/_13C0:_17Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 5|.2V0/_13/_13C0:_17Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 4|.2V0/_13/_15C0:_16Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 4|.2V0/_14/_15C0:_16Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 4|.2V0/_15/_15C0:_16Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 5|.2V0/_14/_15C0:_17Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.2V0/_12/_15C0:_15Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.2V0/_13/_15C0:_15Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.2V0/_14/_15C0:_15Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.2V0/_15/_15C0:_15Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 0\ .2V0/_15/_15C0:_18Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 7|.2V0/_14/_15C0:_15Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 7|.2V0/_15/_15C0:_15Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 5|.2V0/_15/_15C0:_17Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 1\.2V0/_13/_15C0:_16Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 1\.2V0/_14/_15C0:_16Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 1\.2V0/_15/_15C0:_16Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 2/.2V0/_16/_16C0:_19Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?3/4Pp1/3Rq
 2/.2V0/_17/_17C0:_20Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?3/4Pp0/3Rq
 2/.2V0/_18/_18C0:_20Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?2/4Pp0/3Rq
 2/.2V0/_19/_19C0:_20Jo0/_1J!0:_31Wo <__0:__0>8Ga0G!0G?1/4Pp0/3Rq
 0\ .2V0/_16/_19C0:_19Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 0\ .2V0/_17/_19C0:_19Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 0\ .2V0/_18/_19C0:_19Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 0\ .2V0/_19/_19C0:_19Jo0/_0J!0:_31Wo <__0:__0>8Ga0G!0G?
 6|.2V0/_13/_19C0:_15Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 1\.2V0/_16/_19C0:_20Jo0/_4J!0:_31Wo <__0:__0>0Ga0G!0G?
 8|.2V0/_16/_19C0:_20Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 8|.2V0/_17/_19C0:_20Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 1\.2V0/_17/_19C0:_20Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 8|.2V0/_18/_19C0:_20Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?
 8|.2V0/_19/_19C0:_20Jo0/_2J!0:_31Wo <__0:__0>8Ga0G!0G?
 1\.2V0/_18/_19C0:_21Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 7|.2V0/_16/_19C0:_20Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?
 7|.2V0/_17/_19C0:_20Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?
 6|.2V0/_14/_19C0:_21Jo0/_6J!0:_31Wo <__0:__0>0Ga0G!0G?
 6|.2V0/_15/_19C0:_21Jo0/_6J!0:_31Wo <__0:__0>0Ga0G!0G?
 5|.2V0/_16/_19C0:_21Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 5|.2V0/_17/_19C0:_21Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 4|.2V0/_16/_19C0:_21Jo0/_5J!0:_31Wo <__0:__0>0Ga0G!0G?
 4|.2V0/_17/_19C0:_21Jo0/_4J!0:_31Wo <__0:__0>0Ga0G!0G?
 4|.2V0/_18/_19C0:_21Jo0/_4J!0:_31Wo <__0:__0>0Ga0G!0G?
 4|.2V0/_19/_19C0:_21Jo0/_3J!0:_31Wo <__0:__0>8Ga0G!0G?
 7|.2V0/_18/_19C0:_20Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 7|.2V0/_19/_19C0:_20Jo0/_1J!0:_31Wo <__0:__0>8Ga0G!0G?
 1\.2V0/_19/_19C0:_21Jo0/_1J!0:_31Wo <__0:__0>8Ga0G!0G?
 2/.2V0/_20/_20C0:_22Jo0/_0J!0:_31Wo <__0:__0>9Ga0G!0G?2/4Pp0/3Rq
 2/.2V0/_21/_21C0:_22Jo0/_0J!0:_31Wo <__0:__0>9Ga0G!0G?1/4Pp0/3Rq
 4|.2V0/_20/_21C0:_21Jo0/_0J!0:_31Wo <__0:__0>9Ga0G!0G?
 4|.2V0/_21/_21C0:_21Jo0/_0J!0:_31Wo <__0:__0>9Ga0G!0G?
 1\.2V0/_20/_21C0:_21Jo0/_1J!0:_31Wo <__0:__0>9Ga0G!0G?
 1\.2V0/_21/_21C0:_21Jo0/_1J!0:_31Wo <__0:__0>9Ga0G!0G?
 5|.2V0/_18/_21C0:_21Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 5|.2V0/_19/_21C0:_21Jo0/_1J!0:_31Wo <__0:__0>8Ga0G!0G?
 5|.2V0/_20/_21C0:_21Jo0/_1J!0:_31Wo <__0:__0>9Ga0G!0G?
 5|.2V0/_21/_21C0:_21Jo0/_1J!0:_31Wo <__0:__0>9Ga0G!0G?
 6|.2V0/_16/_19C0:_21Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 6|.2V0/_17/_19C0:_21Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 6|.2V0/_18/_19C0:_21Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 6|.2V0/_19/_19C0:_21Jo0/_1J!0:_31Wo <__0:__0>8Ga0G!0G?
 6|.2V0/_20/_21C0:_21Jo0/_0J!0:_31Wo <__0:__0>9Ga0G!0G?
 6|.2V0/_21/_21C0:_21Jo0/_0J!0:_31Wo <__0:__0>9Ga0G!0G?
 0\ v4V0/_20/_21C0:_24Jo0/_3J!0:_31Wo <__0:__0>9Ga0G!0G?
 7|.4V0/_20/_21C0:_24Jo0/_4J!0:_31Wo <__0:__0>9Ga0G!0G?
 7|.4V0/_21/_21C0:_24Jo0/_2J!0:_31Wo <__0:__0>9Ga0G!0G?
 1/.4V0/_22/_22C0:_25Jo0/_0J!0:_31Wo <__0:__0>9Ga0G!0G?3/4Pp1/3Rq
 2\.4V0/_22/_22C0:_26Jo0/_2J!0:_31Wo <__0:__0>9Ga0G!0G?
 7|.4V0/_22/_22C0:_24Jo0/_1J!0:_31Wo <__0:__0>9Ga0G!0G?
 1/.4V0/_23/_23C0:_26Jo0/_1J!0:_31Wo <__0:__0>9Ga0G!0G?3/4Pp0/3Rq
 1/.4V0/_24/_24C0:_26Jo0/_1J!0:_31Wo <__0:__0>9Ga0G!0G?2/4Pp0/3Rq
 1/.4V0/_25/_25C0:_26Jo0/_1J!0:_31Wo <__0:__0>9Ga0G!0G?1/4Pp0/3Rq
 0\ .4V0/_21/_22C0:_26Jo0/_5J!0:_31Wo <__0:__0>9Ga0G!0G?
 2\.4V0/_23/_25C0:_26Jo0/_1J!0:_31Wo <__0:__0>9Ga0G!0G?
 2\.4V0/_24/_25C0:_26Jo0/_1J!0:_31Wo <__0:__0>9Ga0G!0G?
 2\.4V0/_25/_25C0:_26Jo0/_1J!0:_31Wo <__0:__0>9Ga0G!0G?
 1/.4V0/_26/_26C0:_26Jo0/_0J!0:_31Wo <__0:__0>9Ga0G!0G?0/4Pp0/3Rq
 2\.4V0/_26/_26C0:_27Jo0/_1J!0:_31Wo <__0:__0>9Ga0G!0G?
 1/.4V0/_27/_27C0:_27Jo0/_0J!0:_31Wo <__0:__0>9Ga0G!0G?0/4Pp0/3Rq
 1 [ /.4V0/_27/_27C0:_27Jo0/_0J!0:_31Wo <__0:__0>9Ga0G!0G?0/4Pp0/3Rq
 4|.4V0/_22/_27C0:_25Jo0/_0J!0:_31Wo <__0:__0>9Ga0G!0G?
 8|.4V0/_20/_27C0:_26Jo0/_6J!0:_31Wo <__0:__0>9Ga0G!0G?
 3|.2V0/_16/_21C0:_24Jo0/_7J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.2V0/_17/_21C0:_24Jo0/_7J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.2V0/_18/_21C0:_24Jo0/_7J!0:_31Wo <__0:__0>0Ga0G!0G?
 1 ] /.4V23/_27/_27C0:_28Jo0/_0J!0:_31Wo <__0:__0>11Ga0G!0G?1/4Pp0/3Rq
 4|.4V0/_23/_27C0:_28Jo0/_3J!0:_31Wo <__0:__0>9Ga0G!0G?
 4|.4V0/_24/_27C0:_28Jo0/_3J!0:_31Wo <__0:__0>9Ga0G!0G?
 4|.4V0/_25/_27C0:_28Jo0/_3J!0:_31Wo <__0:__0>9Ga0G!0G?
 2\.4V0/_27/_27C0:_28Jo0/_1J!0:_31Wo <__0:__0>9Ga0G!0G?
 2 [ \.4V0/_27/_27C0:_28Jo0/_1J!0:_31Wo <__0:__0>9Ga0G!0G?
 6|.4V0/_22/_27C0:_28Jo0/_3J!0:_31Wo <__0:__0>9Ga0G!0G?
 6|.4V0/_23/_27C0:_28Jo0/_3J!0:_31Wo <__0:__0>9Ga0G!0G?
 6|.4V0/_24/_27C0:_28Jo0/_3J!0:_31Wo <__0:__0>9Ga0G!0G?
 6|.4V0/_25/_27C0:_28Jo0/_3J!0:_31Wo <__0:__0>9Ga0G!0G?
 0\ .4V0/_22/_27C0:_29Jo0/_3J!0:_31Wo <__0:__0>9Ga0G!0G?
 0\ .4V0/_23/_27C0:_29Jo0/_3J!0:_31Wo <__0:__0>9Ga0G!0G?
 0\ .4V0/_24/_27C0:_29Jo0/_3J!0:_31Wo <__0:__0>9Ga0G!0G?
 0\ .4V0/_25/_27C0:_29Jo0/_3J!0:_31Wo <__0:__0>9Ga0G!0G?
 0\ .4V0/_26/_27C0:_29Jo0/_3J!0:_31Wo <__0:__0>9Ga0G!0G?
 0\ .4V0/_27/_27C0:_29Jo0/_3J!0:_31Wo <__0:__0>9Ga0G!0G?
 0 [ \ .4V0/_27/_27C0:_29Jo0/_3J!0:_31Wo <__0:__0>9Ga0G!0G?
 6|.4V0/_26/_27C0:_28Jo0/_2J!0:_31Wo <__0:__0>9Ga0G!0G?
 6|.4V0/_27/_27C0:_28Jo0/_2J!0:_31Wo <__0:__0>9Ga0G!0G?
 6 [ |.4V0/_27/_27C0:_28Jo0/_2J!0:_31Wo <__0:__0>9Ga0G!0G?
 3|.2V0/_19/_21C0:_24Jo0/_4J!0:_31Wo <__0:__0>8Ga0G!0G?
 3|.2V0/_20/_21C0:_24Jo0/_4J!0:_31Wo <__0:__0>9Ga0G!0G?
 3|.2V0/_21/_21C0:_24Jo0/_4J!0:_31Wo <__0:__0>9Ga0G!0G?
 0 ] \ .4V23/_27/_27C0:_29Jo0/_0J!0:_31Wo <__0:__0>11Ga0G!0G?
 4|.4V0/_26/_27C0:_28Jo0/_3J!0:_31Wo <__0:__0>9Ga0G!0G?
 2 ] \.4V23/_27/_27C0:_29Jo0/_0J!0:_31Wo <__0:__0>11Ga0G!0G?
 4|.4V0/_27/_27C0:_28Jo0/_1J!0:_31Wo <__0:__0>9Ga0G!0G?
 4 [ |.4V0/_27/_27C0:_28Jo0/_1J!0:_31Wo <__0:__0>9Ga0G!0G?
 6 ] |.4V23/_27/_27C0:_28Jo0/_0J!0:_31Wo <__0:__0>11Ga0G!0G?
 4 ] |.4V23/_27/_27C0:_28Jo0/_0J!0:_31Wo <__0:__0>11Ga0G!0G?
 1/.4V23/_28/_28C0:_31Jo0/_0J!0:_31Wo <__0:__0>11Ga0G!0G?3/4Pp1/3Rq
 1/.4V23/_29/_29C1:_32Jo0/_1J!0:_31Wo <__0:__0>12Ga0G!0G?3/4Pp0/3Rq
 1/.4V23/_30/_30C1:_32Jo0/_1J!0:_31Wo <__0:__0>12Ga0G!0G?2/4Pp0/3Rq
 1/.4V23/_31/_31C1:_32Jo0/_1J!0:_31Wo <__0:__0>12Ga0G!0G?1/4Pp0/3Rq
 7|.4V0/_23/_31C0:_31Jo0/_7J!0:_31Wo <__0:__0>9Ga0G!0G?
 7|.4V0/_24/_31C0:_31Jo0/_7J!0:_31Wo <__0:__0>9Ga0G!0G?
 7|.4V0/_25/_31C0:_31Jo0/_7J!0:_31Wo <__0:__0>9Ga0G!0G?
 7|.4V0/_26/_31C0:_31Jo0/_7J!0:_31Wo <__0:__0>9Ga0G!0G?
 3 < ~.2V0/_21/_21C0:_24Jo0/_3J!0:_31Wo <__0:__0>9Ga0G!0G?
 7|.4V0/_27/_31C0:_31Jo0/_6J!0:_31Wo <__0:__0>9Ga0G!0G?
 7 [ |.4V0/_27/_31C0:_31Jo0/_6J!0:_31Wo <__0:__0>9Ga0G!0G?
 7 ] |.4V23/_27/_31C0:_31Jo0/_0J!0:_31Wo <__0:__0>11Ga0G!0G?
 7|.4V23/_28/_31C0:_31Jo0/_0J!0:_31Wo <__0:__0>11Ga0G!0G?
 7|.4V23/_29/_31C0:_31Jo0/_0J!0:_31Wo <__0:__0>12Ga0G!0G?
 7|.4V23/_30/_31C0:_31Jo0/_0J!0:_31Wo <__0:__0>12Ga0G!0G?
 7|.4V23/_31/_31C0:_31Jo0/_0J!0:_31Wo <__0:__0>12Ga0G!0G?
 5 < ~.2V0/_21/_21C0:_21Jo0/_0J!0:_31Wo <__0:__0>9Ga0G!0G?
 3 > |.2V23/_23/_23C0:_24Jo0/_3J!0:_31Wo <__0:_27>nullGa0G!0G?
```
</details>

**Comment by matklad** [comment] 2024-02-24 22:05
Another dupe of https://github.com/tigerbeetle/tigerbeetle/issues/1532

**Comment by sentientwaffle** [comment] 2024-02-27 21:22
Fixed by https://github.com/tigerbeetle/tigerbeetle/pull/1598.

**Closed as completed by sentientwaffle** 2024-02-27 21:22 UTC
